# Generated by Django 5.1.6 on 2025-02-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(null=True, upload_to="images/")),
                ("eloRating", models.IntegerField(default=1000)),
                ("answer", models.CharField(max_length=50)),
                ("hint", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("puzzleType", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("eloRating", models.IntegerField(default=1000)),
                ("fistName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
